apiVersion: v1
kind: Template
metadata:
  name: thoth-build-watcher-buildconfig
  annotations:
    description: >
      This is Thoth Build Watcher BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Build Watcher BuildConfig'
    version: 0.2.0
    tags: thoth,build-watcher,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Build Watcher BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: thoth-build-watcher-buildconfig
    app: thoth
    component: thoth-build-watcher

parameters:
  - description: Name of the github repository for Thoth's Build Watcher
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/build-watcher'

  - description: Git reference to be used for Thoth's Build Watcher
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: thoth-build-watcher
      annotations:
        thoth-station.ninja/template-version: 0.2.0
      labels:
        app: thoth
        component: thoth-build-watcher
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "thoth-build-watcher:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py38:latest
          env:
            - name: UPGRADE_PIP_TO_LATEST
              value: ""
            # Pass this if you want to switch to vanilla ubi/fedora/... s2i container images.
            - name: ENABLE_MICROPIPENV
              value: "1"
            # See https://github.com/thoth-station/s2i-thoth for info.
            - name: THOTH_CONFIG_CHECK
              value: "1"
            - name: THOTH_PROVENANCE_CHECK
              value: "1"
            - name: THOTH_DRY_RUN
              value: "1"
            - name: THOTH_ERROR_FALLBACK
              value: "1"
            - name: THOTH_ADVISE
              value: "1"
            - name: THAMOS_VERBOSE
              value: "1"
            - name: THAMOS_DEBUG
              value: "0"
            - name: THAMOS_CONFIG_EXPAND_ENV
              value: "1"
            - name: THAMOS_CONFIG_TEMPLATE
              value: ".thoth.yaml"
