apiVersion: v1
kind: Template
metadata:
  name: build-watcher-imagestream
  annotations:
    description: >
      This is Build Watcher ImageStream,
      this template is meant to be used by Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Build Watcher'
    version: 0.1.0
    tags: poc,thoth,build-watcher,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Build Watcher ImageStream, this template is meant to be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: build-watcher-imagestream
    app: thoth
    component: build-watcher

parameters:
  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: build-watcher
      name: build-watcher
    spec:
      name: ${IMAGE_STREAM_TAG}
      lookupPolicy:
        local: true
