apiVersion: v1
kind: Template
metadata:
  name: thoth-build-watcher-sa
  annotations:
    description: This is Thoth - Build Watcher
    openshift.io/display-name: 'Thoth Core: Build Watcher'
    version: 0.1.0
    tags: poc,thoth,build-watcher,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Build
      Watcher on OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: thoth-build-watcher-sa
    app: thoth
    component: thoth-build-watcher

parameters:
  - description: Namespace on which Build Watcher should listen to builds.
    displayName: Build Watcher namespace
    required: true
    name: THOTH_WATCHED_NAMESPACE

objects:
  - kind: RoleBinding
    apiVersion: v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      name: "build-watcher-${THOTH_WATCHED_NAMESPACE}"
      labels:
        app: thoth
        component: thoth-build-watcher
    roleRef:
      kind: ClusterRole
      name: edit
    subjects:
      - kind: ServiceAccount
        name: "build-watcher-${THOTH_WATCHED_NAMESPACE}"
        namespace: "${THOTH_WATCHED_NAMESPACE}"

  - kind: ServiceAccount
    apiVersion: v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      name: "build-watcher-${THOTH_WATCHED_NAMESPACE}"
      namespace: "${THOTH_WATCHED_NAMESPACE}"
      labels:
        app: thoth
        component: thoth-build-watcher
    automountServiceAccountToken: true
